#!/usr/bin/env bash
# Run SLINK generated in the specified BUILDDIR.
#
# This provides the same feature as "ninja run", except that it is possible to
# pass arguments to SLINK.
#
# Syntax: ./run BUILDDIR <SLINK options ...>
if [[ $# = 0 ]]
then
    echo "Syntax: $0 BUILDDIR <SLINK options>" >&2
    exit 1
fi

BUILDDIR="$1"
shift

if [[ ! -d "$BUILDDIR" ]]
then
    echo "The build dir \"$BUILDDIR\" does not exist." >&2
    exit 1
fi

SLINK_ICON_DIR="app/data" \
SLINK_SERVER_PATH="$BUILDDIR/server/SLINK-server" \
"$BUILDDIR/app/SLINK" "$@"
